[GLOBAL]
pants_version = "2.33.0.dev0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.codegen.protobuf.python",
  "pants.backend.codegen.protobuf.lint.buf",
]

[source]
root_patterns = ["/", "/gen"]

[python-repos]
indexes = ["https://pypi.org/simple/", "https://buf.build/gen/python"]

[python]
interpreter_constraints = ["CPython>=3.10,<4"]
enable_resolves = true
default_resolve = "python-default"

[python.resolves]
python-default = "3rdparty/python-default.lock"

[anonymous-telemetry]
enabled = false
